/* ── MERKEZİ PARFÜM VERİTABANI ── */
const perfumeDB = [
  // XERJOFF (10)
  { name: "Naxos", brand: "Xerjoff", family: "yogun", notes: { top: ["lavanta", "bergamot", "limon"], mid: ["bal", "tarçın", "kaşmir", "yasemin"], base: ["tütün", "vanilya", "tonka"] } },
  { name: "Erba Pura", brand: "Xerjoff", family: "orta", notes: { top: ["portakal", "limon", "bergamot"], mid: ["meyvemsi notalar"], base: ["amber", "beyaz misk", "madagaskar vanilyası"] } },
  { name: "Alexandria II", brand: "Xerjoff", family: "yogun", notes: { top: ["elma", "tarçın", "gül ağacı", "lavanta"], mid: ["sedir", "vadi zambağı", "gül"], base: ["amber", "misk", "oud", "sandal ağacı", "vanilya"] } },
  { name: "Renaissance", brand: "Xerjoff", family: "hafif", notes: { top: ["limon", "tangerine", "bergamot", "petitgrain"], mid: ["nane", "vadi zambağı", "gül"], base: ["amber", "misk", "sedir", "patchouli"] } },
  { name: "Accento", brand: "Xerjoff", family: "orta", notes: { top: ["ananas", "sümbül"], mid: ["yasemin", "iris", "pembe biber"], base: ["misk", "amber", "vetiver", "patchouli", "vanilya"] } },
  { name: "Mefisto", brand: "Xerjoff", family: "hafif", notes: { top: ["greyfurt", "bergamot", "limon"], mid: ["lavanta", "iris", "gül"], base: ["misk", "sedir", "amber", "sandal ağacı"] } },
  { name: "Uden", brand: "Xerjoff", family: "orta", notes: { top: ["limon", "greyfurt", "citron"], mid: ["rom", "gül", "sandal ağacı", "guaiac ağacı"], base: ["vanilya", "kahve", "misk", "ambergris"] } },
  { name: "Tony Iommi Monkey Special", brand: "Xerjoff", family: "yogun", notes: { top: ["rom", "çarkıfelek meyvesi", "bergamot", "sardunya"], mid: ["tarçın", "patchouli", "deri", "bulgar gülü"], base: ["karamel", "vanilya", "tonka", "sandal ağacı", "misk"] } },
  { name: "Torino21", brand: "Xerjoff", family: "hafif", notes: { top: ["nane", "limon", "fesleğen", "biberiye"], mid: ["lavanta", "yasemin", "frenk üzümü"], base: ["misk", "lemon verbena"] } },
  { name: "Kobe", brand: "Xerjoff", family: "orta", notes: { top: ["portakal", "bergamot", "labdanum"], mid: ["neroli", "petitgrain", "portakal çiçeği"], base: ["gül ağacı", "benzoin", "amber", "misk", "tonka"] } },

  // NIŞANE (10)
  { name: "Hacivat", brand: "Nishane", family: "yogun", notes: { top: ["ananas", "greyfurt", "bergamot"], mid: ["sedir", "patchouli", "yasemin"], base: ["meşe yosunu", "odunsu notalar"] } },
  { name: "Ani", brand: "Nishane", family: "yogun", notes: { top: ["zencefil", "bergamot", "pembe biber", "yeşil notalar"], mid: ["kardelen", "siyah frenk üzümü", "türk gülü"], base: ["vanilya", "benzoin", "sandal ağacı", "misk", "patchouli", "sedir", "ambergris"] } },
  { name: "Hundred Silent Ways", brand: "Nishane", family: "orta", notes: { top: ["sümbülteber", "şeftali", "mandalina"], mid: ["gardenya", "yasemin", "iris"], base: ["vanilya", "sandal ağacı", "vetiver"] } },
  { name: "Fan Your Flames", brand: "Nishane", family: "yogun", notes: { top: ["hindistan cevizi", "rom"], mid: ["tütün", "tonka fasulyesi"], base: ["meşe yosunu", "sedir ağacı"] } },
  { name: "Wulong Cha", brand: "Nishane", family: "hafif", notes: { top: ["bergamot", "portakal", "litsea cubeba", "mandalina"], mid: ["oolong çayı", "hindistan cevizi"], base: ["misk", "incir"] } },
  { name: "Ege / ΑΙΓΑΙΟ", brand: "Nishane", family: "hafif", notes: { top: ["yuzu", "menekşe yaprağı", "anason"], mid: ["fesleğen", "yeşil kakule", "nane"], base: ["olibanum", "meyan kökü"] } },
  { name: "Karagoz", brand: "Nishane", family: "yogun", notes: { top: ["üzüm", "ananas", "bitkisel notalar"], mid: ["neroli", "yasemin", "patchouli"], base: ["vetiver", "oud", "amber"] } },
  { name: "Sultan Vetiver", brand: "Nishane", family: "orta", notes: { top: ["java vetiver", "anason", "karabiber", "bergamot"], mid: ["bourbon vetiver", "haiti vetiver", "neroli", "tonka"], base: ["amber", "deri", "brezilya vetiveri"] } },
  { name: "B-612", brand: "Nishane", family: "orta", notes: { top: ["lavanta", "sardunya", "servi"], mid: ["kaşmir ağacı", "sedir", "sandal ağacı", "patchouli"], base: ["misk", "meşe yosunu", "tonka"] } },
  { name: "Vain & Naive", brand: "Nishane", family: "orta", notes: { top: ["portakal", "bergamot"], mid: ["türk gülü", "yasemin", "sedir", "erik", "ahududu"], base: ["sandal ağacı", "amber", "patchouli", "tonka", "misk", "benzoin"] } },

  // CREED (10)
  { name: "Aventus", brand: "Creed", family: "orta", notes: { top: ["ananas", "bergamot", "frenk üzümü", "elma"], mid: ["nyrk ağacı", "patchouli", "yasemin", "gül"], base: ["misk", "meşe yosunu", "ambergris", "vanilya"] } },
  { name: "Green Irish Tweed", brand: "Creed", family: "orta", notes: { top: ["limon otu", "iris"], mid: ["menekşe yaprağı"], base: ["ambergris", "sandal ağacı"] } },
  { name: "Silver Mountain Water", brand: "Creed", family: "hafif", notes: { top: ["bergamot", "mandalina"], mid: ["yeşil çay", "siyah frenk üzümü"], base: ["misk", "petitgrain", "sandal ağacı", "galbanum"] } },
  { name: "Millésime Impérial", brand: "Creed", family: "hafif", notes: { top: ["deniz notaları", "meyvemsi notalar"], mid: ["sicilya limonu", "bergamot", "mandalina", "iris"], base: ["misk", "odunsu notalar", "deniz notaları"] } },
  { name: "Virgin Island Water", brand: "Creed", family: "hafif", notes: { top: ["hindistan cevizi", "misket limonu", "beyaz bergamot", "sicilya mandalinası"], mid: ["zencefil", "ylang-ylang", "yasemin", "ebemkuşağı"], base: ["beyaz rom", "şeker kamışı", "misk"] } },
  { name: "Royal Oud", brand: "Creed", family: "yogun", notes: { top: ["limon", "pembe biber", "sicilya bergamotu"], mid: ["sedir", "angelica", "galbanum"], base: ["sandal ağacı", "oud", "misk"] } },
  { name: "Original Santal", brand: "Creed", family: "orta", notes: { top: ["sandal ağacı", "tarçın", "kişniş", "ardıç meyvesi"], mid: ["lavanta", "zencefil", "biberiye", "petitgrain"], base: ["vanilya", "ambergris"] } },
  { name: "Original Vetiver", brand: "Creed", family: "hafif", notes: { top: ["bergamot", "zencefil", "mandalina"], mid: ["haiti vetiveri", "sandal ağacı", "iris"], base: ["misk", "ambergris"] } },
  { name: "Himalaya", brand: "Creed", family: "orta", notes: { top: ["bergamot", "greyfurt", "limon", "mandalina"], mid: ["pembe biber", "ardıç meyvesi", "hindistan cevizi", "sandal ağacı", "sedir", "barut"], base: ["misk", "ambergris", "sedir"] } },
  { name: "Viking", brand: "Creed", family: "orta", notes: { top: ["pembe biber", "nane", "bergamot", "limon", "absinthe", "turuncu"], mid: ["lavanta", "bulgar gülü", "karanfil", "yenibahar", "yasemin", "neroli"], base: ["vetiver", "sedir", "beyaz misk", "sandal ağacı"] } },

  // DIOR (10)
  { name: "Sauvage Elixir", brand: "Dior", family: "yogun", notes: { top: ["tarçın", "kakule", "greyfurt"], mid: ["lavanta"], base: ["meyan kökü", "sandal ağacı", "amber", "patchouli"] } },
  { name: "Sauvage EDP", brand: "Dior", family: "orta", notes: { top: ["bergamot"], mid: ["lavanta", "yıldız anason", "hindistan cevizi"], base: ["ambroxan", "vanilya"] } },
  { name: "Sauvage EDT", brand: "Dior", family: "hafif", notes: { top: ["bergamot", "karabiber"], mid: ["lavanta", "sichuan biberi", "pembe biber", "vetiver", "patchouli"], base: ["cedar", "labdanum", "ambroxan"] } },
  { name: "Dior Homme Intense", brand: "Dior", family: "yogun", notes: { top: ["lavanta"], mid: ["iris", "ambrette", "armut"], base: ["sedir", "vetiver"] } },
  { name: "Dior Homme Parfum", brand: "Dior", family: "yogun", notes: { top: ["toscana irisi", "italyan portakalı"], mid: ["deri", "gül"], base: ["sandal ağacı", "oud", "sedir", "amber"] } },
  { name: "Fahrenheit", brand: "Dior", family: "yogun", notes: { top: ["lavanta", "mandalina", "alıç", "hindistan cevizi çiçeği", "sedir", "bergamot", "papatya", "limon"], mid: ["hindistan cevizi", "hanımeli", "karanfil", "sandal ağacı", "menekşe yaprağı", "yasemin", "vadi zambağı", "sedir"], base: ["deri", "tonka fasulyesi", "amber", "patchouli", "misk", "vetiver"] } },
  { name: "Dior Homme Sport", brand: "Dior", family: "hafif", notes: { top: ["limon", "bergamot", "aldahitler"], mid: ["elemi", "pembe biber"], base: ["odunsu notalar", "olibanum", "amber"] } },
  { name: "Dior Homme 2020", brand: "Dior", family: "orta", notes: { top: ["bergamot", "pembe biber", "elemi"], mid: ["kaşmir ağacı", "atlas sediri", "patchouli"], base: ["iso e super", "haiti vetiveri", "beyaz misk"] } },
  { name: "Eau Sauvage", brand: "Dior", family: "hafif", notes: { top: ["limon", "bergamot", "fesleğen", "biberiye", "kimyon", "meyvemsi notalar"], mid: ["yasemin", "kişniş", "karanfil", "patchouli", "sandal ağacı", "gül", "nane"], base: ["meşe yosunu", "vetiver", "misk", "amber"] } },
  { name: "Ambre Nuit", brand: "Dior", family: "orta", notes: { top: ["bergamot", "greyfurt"], mid: ["türk gülü", "pembe biber"], base: ["amber", "guaiac ağacı", "sedir", "patchouli"] } },

  // CHANEL (5)
  { name: "Bleu de Chanel Parfum", brand: "Chanel", family: "yogun", notes: { top: ["limon otu", "bergamot", "nane"], mid: ["lavanta", "geranium", "yeşil notalar"], base: ["sandal ağacı", "sedir", "amberwood", "tonka"] } },
  { name: "Bleu de Chanel EDP", brand: "Chanel", family: "orta", notes: { top: ["greyfurt", "limon", "nane", "pembe biber"], mid: ["zencefil", "yasemin", "hindistan cevizi"], base: ["tütsü", "amber", "sedir", "sandal ağacı", "patchouli"] } },
  { name: "Allure Homme Sport", brand: "Chanel", family: "hafif", notes: { top: ["portakal", "deniz notaları", "aldahitler", "kan mandalinası"], mid: ["karabiber", "neroli", "sedir"], base: ["tonka fasulyesi", "vanilya", "beyaz misk", "amber", "vetiver", "elemi reçinesi"] } },
  { name: "Allure Homme Sport Eau Extrême", brand: "Chanel", family: "orta", notes: { top: ["mandalina", "nane", "selvi", "adaçayı"], mid: ["karabiber"], base: ["tonka fasulyesi", "misk", "sandal ağacı", "sedir"] } },
  { name: "Allure Homme", brand: "Chanel", family: "orta", notes: { top: ["limon", "şeftali", "zencefil", "mandalina", "lavanta", "bergamot"], mid: ["karabiber", "sedir", "patchouli", "gardenya", "gül", "yasemin"], base: ["sandal ağacı", "vanilya", "tonka", "amber", "misk", "benzoin"] } },
  { name: "Platinum Égoïste", brand: "Chanel", family: "orta", notes: { top: ["lavanta", "biberiye", "petitgrain", "neroli"], mid: ["sardunya", "adaçayı", "galbanum", "yasemin"], base: ["meşe yosunu", "vetiver", "sedir", "sandal ağacı", "amber"] } },

  // ARMANI (10)
  { name: "Acqua di Gio Profondo", brand: "Giorgio Armani", family: "orta", notes: { top: ["deniz notaları", "aquozone", "bergamot", "mandalina"], mid: ["biberiye", "lavanta", "cypress", "sakız ağacı"], base: ["mineral notalar", "misk", "patchouli", "amber"] } },
  { name: "Acqua di Gio Parfum", brand: "Giorgio Armani", family: "orta", notes: { top: ["deniz notaları", "bergamot"], mid: ["biberiye", "adaçayı", "geranium"], base: ["olibanum", "patchouli"] } },
  { name: "Acqua di Gio Profumo", brand: "Giorgio Armani", family: "yogun", notes: { top: ["deniz notaları", "bergamot"], mid: ["biberiye", "adaçayı", "geranium"], base: ["tütsü", "patchouli"] } },
  { name: "Armani Code Parfum", brand: "Giorgio Armani", family: "yogun", notes: { top: ["bergamot", "bergamot yaprağı"], mid: ["iris", "adaçayı", "aldehitler", "iris kökü"], base: ["tonka fasulyesi", "sedir ağacı"] } },
  { name: "Armani Code Eau de Toilette", brand: "Giorgio Armani", family: "hafif", notes: { top: ["limon", "bergamot"], mid: ["yıldız anason", "zeytin çiçeği", "guaiac ağacı"], base: ["deri", "tütün", "tonka fasulyesi"] } },
  { name: "Stronger With You", brand: "Giorgio Armani", family: "yogun", notes: { top: ["kestane", "şeker"], mid: ["adaçayı", "lavanta"], base: ["vanilya", "amberwood"] } },
  { name: "Stronger With You Intensely", brand: "Giorgio Armani", family: "yogun", notes: { top: ["pembe biber", "ardıç", "menekşe"], mid: ["toffee", "tarçın", "adaçayı", "lavanta"], base: ["vanilya", "tonka fasulyesi", "amber", "süet"] } },
  { name: "Stronger With You Absolutely", brand: "Giorgio Armani", family: "yogun", notes: { top: ["rom", "elemi", "bergamot"], mid: ["lavanta", "adaçayı"], base: ["kestane", "madagaskar vanilyası", "sedir", "patchouli"] } },
  { name: "Acqua di Gio Eau de Toilette", brand: "Giorgio Armani", family: "hafif", notes: { top: ["kireç", "limon", "bergamot", "yasemin", "portakal", "mandalina", "neroli"], mid: ["deniz notaları", "yasemin", "calone", "şeftali", "frezye", "biberiye", "siklamen", "menekşe", "kişniş", "hindistan cevizi", "gül", "mignonette"], base: ["beyaz misk", "sedir", "meşe yosunu", "patchouli", "amber"] } },
  { name: "Armani Prive Oud Royal", brand: "Giorgio Armani", family: "yogun", notes: { top: ["safran"], mid: ["oud", "gül"], base: ["amber", "sandal ağacı", "tütsü"] } },

  // MANCERA (10)
  { name: "Cedrat Boise", brand: "Mancera", family: "orta", notes: { top: ["sicilya limonu", "frenk üzümü", "bergamot", "baharatlar"], mid: ["meyvemsi notalar", "patchouli yaprağı", "su yasemini"], base: ["sedir", "deri", "sandal ağacı", "vanilya", "yosun", "misk"] } },
  { name: "Red Tobacco", brand: "Mancera", family: "yogun", notes: { top: ["tarçın", "oud", "safran", "tütsü", "hindistan cevizi", "yeşil elma", "beyaz armut"], mid: ["patchouli", "yasemin"], base: ["tütün", "madagaskar vanilyası", "amber", "sandal ağacı", "guaiac ağacı", "beyaz misk", "haiti vetiveri"] } },
  { name: "Instant Crush", brand: "Mancera", family: "yogun", notes: { top: ["safran", "zencefil", "sicilya bergamotu", "sicilya mandalinası"], mid: ["amberwood", "fas gülü", "mısır yasemini", "endonezya patchouli yaprağı"], base: ["madagaskar vanilyası", "beyaz misk", "sandal ağacı", "meşe yosunu"] } },
  { name: "Holidays", brand: "Mancera", family: "hafif", notes: { top: ["hindistan cevizi", "bergamot"], mid: ["tiare çiçeği", "ylang-ylang", "deniz notaları"], base: ["vanilya", "sandal ağacı", "beyaz misk"] } },
  { name: "Lemon Line", brand: "Mancera", family: "hafif", notes: { top: ["limon", "portakal", "lavanta"], mid: ["beyaz çiçekler", "amber", "geranium"], base: ["beyaz misk", "meşe yosunu"] } },
  { name: "Black Gold", brand: "Mancera", family: "yogun", notes: { top: ["lavanta", "tarçın", "hindistan cevizi", "citrus", "agarwood"], mid: ["menekşe", "yasemin", "patchouli", "gül", "deniz notaları"], base: ["deri", "odunsu notalar", "beyaz misk", "amber", "vetiver"] } },
  { name: "Saharian Wind", brand: "Mancera", family: "orta", notes: { top: ["baharatlar", "deri", "bergamot", "pembe biber"], mid: ["selvi", "lavanta", "vadi zambağı"], base: ["tütün", "vanilya", "amber", "beyaz misk", "patchouli", "odunsu notalar"] } },
  { name: "Hindu Kush", brand: "Mancera", family: "yogun", notes: { top: ["baharatlar", "kenevir", "tütsü", "labdanum"], mid: ["patchouli", "odunsu notalar"], base: ["amber", "guaiac ağacı", "vanilya", "beyaz misk"] } },
  { name: "Kumkat Wood", brand: "Mancera", family: "hafif", notes: { top: ["greyfurt", "baharatlar", "bergamot"], mid: ["çiçeksi notalar", "patchouli", "amber"], base: ["sedir", "beyaz misk", "sandal ağacı", "vetiver"] } },
  { name: "Roses Vanille", brand: "Mancera", family: "orta", notes: { top: ["limon", "su notaları"], mid: ["gül", "şeker"], base: ["vanilya", "şeker", "beyaz misk", "sedir"] } },

  // TOM FORD (10)
  { name: "Black Orchid", brand: "Tom Ford", family: "yogun", notes: { top: ["trüf", "gardenya", "frenk üzümü", "ylang-ylang", "yasemin", "bergamot", "mandalina", "limon"], mid: ["orkide", "baharatlar", "meyvemsi notalar", "nilüfer"], base: ["çikolata", "patchouli", "vanilya", "tütsü", "amber", "sandal ağacı", "vetiver", "misk"] } },
  { name: "Oud Wood", brand: "Tom Ford", family: "orta", notes: { top: ["gül ağacı", "kakule", "sichuan biberi"], mid: ["oud", "sandal ağacı", "vetiver"], base: ["tonka", "vanilya", "amber"] } },
  { name: "Ombré Leather", brand: "Tom Ford", family: "yogun", notes: { top: ["kakule"], mid: ["deri", "yasemin sambac"], base: ["amber", "yosun", "patchouli"] } },
  { name: "Tobacco Vanille", brand: "Tom Ford", family: "yogun", notes: { top: ["tütün yaprağı", "baharatlı notalar"], mid: ["vanilya", "kakao", "tonka fasulyesi", "tütün çiçeği"], base: ["kurutulmuş meyveler", "odunsu notalar"] } },
  { name: "Grey Vetiver", brand: "Tom Ford", family: "hafif", notes: { top: ["greyfurt", "portakal çiçeği", "adaçayı"], mid: ["hindistan cevizi", "orris kökü", "yenibahar"], base: ["vetiver", "odunsu notalar", "amber", "meşe yosunu"] } },
  { name: "Costa Azzurra", brand: "Tom Ford", family: "hafif", notes: { top: ["driftwood", "deniz yosunu", "agarwood", "kakule", "kereviz tohumu", "ebemkuşağı"], mid: ["limon", "lavanta", "ardıç", "sarı mandalina", "pelu otu", "mersin"], base: ["vetiver", "meşe", "tütsü", "sakız", "olibanum", "vanilya"] } },
  { name: "Neroli Portofino", brand: "Tom Ford", family: "hafif", notes: { top: ["bergamot", "mandalina", "limon", "acı portakal", "lavanta", "biberiye", "mersin"], mid: ["portakal çiçeği", "neroli", "yasemin", "pitosporum"], base: ["amber", "angelica", "misk çiçeği"] } },
  { name: "Beau de Jour", brand: "Tom Ford", family: "orta", notes: { top: ["lavanta özü", "lavanta"], mid: ["biberiye", "meşe yosunu", "nane", "fesleğen", "geranium"], base: ["patchouli", "amber"] } },
  { name: "Lost Cherry", brand: "Tom Ford", family: "orta", notes: { top: ["vişne", "acı badem", "likör"], mid: ["vişne", "erik", "türk gülü", "yasemin sambac"], base: ["tonka fasulyesi", "vanilya", "peru balsamı", "benzoin", "tarçın", "sandal ağacı", "sedir", "karanfil", "vetiver", "patchouli"] } },
  { name: "Soleil Blanc", brand: "Tom Ford", family: "hafif", notes: { top: ["antep fıstığı", "bergamot", "kardelen", "pembe biber"], mid: ["sümbülteber", "ylang-ylang", "yasemin"], base: ["hindistan cevizi", "amber", "tonka fasulyesi", "benzoin"] } },
  { name: "Soleil Neige", brand: "Tom Ford", family: "hafif", notes: { top: ["bergamot", "havuç tohumu"], mid: ["beyaz çiçekler", "portakal çiçeği", "yasemin", "gül"], base: ["benzoin", "vanilya", "misk"] } },

  // PRADA (10)
  { name: "L'Homme Prada", brand: "Prada", family: "hafif", notes: { top: ["neroli", "karabiber"], mid: ["iris", "amber", "menekşe", "geranium"], base: ["patchouli", "sedir"] } },
  { name: "L'Homme Prada Intense", brand: "Prada", family: "yogun", notes: { top: ["iris"], mid: ["amber", "patchouli"], base: ["tonka fasulyesi", "deri", "sandal ağacı"] } },
  { name: "Luna Rossa Carbon", brand: "Prada", family: "orta", notes: { top: ["bergamot", "karabiber"], mid: ["lavanta", "metalik notalar", "kömür", "su notaları", "toprak notaları"], base: ["ambroxan", "patchouli"] } },
  { name: "Luna Rossa Black", brand: "Prada", family: "yogun", notes: { top: ["bergamot"], mid: ["angelica", "patchouli"], base: ["amber", "coumarin", "misk"] } },
  { name: "Luna Rossa Ocean", brand: "Prada", family: "hafif", notes: { top: ["bergamot", "pembe biber", "artemisia"], mid: ["lavanta", "iris", "adaçayı", "süet", "safran"], base: ["misk", "haiti vetiveri", "patchouli", "karamel"] } },
  { name: "Amber Pour Homme", brand: "Prada", family: "orta", notes: { top: ["neroli", "kardelen", "bergamot", "mandalina"], mid: ["mür", "misk", "portakal çiçeği", "geranium", "vetiver"], base: ["safran", "vanilya", "labdanum", "deri", "sandal ağacı", "tonka fasulyesi", "patchouli"] } },
  { name: "Infusion d'Iris", brand: "Prada", family: "hafif", notes: { top: ["afrika portakal çiçeği", "neroli", "portakal", "mandalina"], mid: ["iris", "sakız ağacı", "galbanum"], base: ["tütsü", "sedir", "benzoin", "vetiver"] } },
  { name: "Luna Rossa Sport", brand: "Prada", family: "hafif", notes: { top: ["ardıç meyveleri", "zencefil"], mid: ["lavanta"], base: ["vanilya", "tonka fasulyesi"] } },
  { name: "Prada Paradoxe", brand: "Prada", family: "orta", notes: { top: ["armut", "tangerine", "bergamot"], mid: ["portakal çiçeği", "yasemin sambac", "neroli özü"], base: ["amber", "beyaz misk", "bourbon vanilyası", "benzoin"] } },
  { name: "Paradigme", brand: "Prada", family: "orta", notes: { top: ["bergamot"], mid: ["iris"], base: ["sedir", "misk"] } },

  // VALENTINO (10)
  { name: "Uomo Born In Roma", brand: "Valentino", family: "orta", notes: { top: ["mineral notalar", "tuz", "menekşe yaprağı"], mid: ["adaçayı", "zencefil"], base: ["odunsu notalar", "vetiver"] } },
  { name: "Uomo Born In Roma Intense", brand: "Valentino", family: "yogun", notes: { top: ["vanilya"], mid: ["lavanta"], base: ["vetiver"] } },
  { name: "Uomo Born In Roma Coral Fantasy", brand: "Valentino", family: "orta", notes: { top: ["kırmızı elma", "kakule", "kalabriya bergamotu"], mid: ["lavanta", "adaçayı", "bourbon sardunya"], base: ["tütün yaprağı", "patchouli", "haiti vetiveri"] } },
  { name: "Uomo Valentino", brand: "Valentino", family: "yogun", notes: { top: ["bergamot", "mersin"], mid: ["fındık", "çikolata", "kavrulmuş kahve çekirdekleri"], base: ["deri", "sedir"] } },
  { name: "Uomo Intense", brand: "Valentino", family: "yogun", notes: { top: ["mandalina", "adaçayı"], mid: ["iris", "tonka fasulyesi"], base: ["deri", "vanilya"] } },
  { name: "Uomo Acqua", brand: "Valentino", family: "hafif", notes: { top: ["mandalina", "domates yaprağı"], mid: ["adaçayı", "patchouli"], base: ["deri", "iris"] } },
  { name: "Born In Roma Yellow Dream", brand: "Valentino", family: "hafif", notes: { top: ["ananas", "mandalina"], mid: ["zencefil", "baharatlar", "zencefilli kurabiye"], base: ["vanilya özü", "sedir"] } },
  { name: "Valentino Donna Born In Roma", brand: "Valentino", family: "orta", notes: { top: ["siyah frenk üzümü", "pembe biber", "bergamot"], mid: ["yasemin", "yasemin sambac", "yasemin çayı"], base: ["bourbon vanilyası", "kaşmir", "guaiac ağacı"] } },
  { name: "Born In Roma Green Stravaganza", brand: "Valentino", family: "hafif", notes: { top: ["kalabriya bergamotu"], mid: ["kahve"], base: ["vetiver"] } },
  { name: "Voce Viva", brand: "Valentino", family: "hafif", notes: { top: ["mandalina", "bergamot", "zencefil"], mid: ["portakal çiçeği", "gardenya"], base: ["vanilya", "meşe yosunu", "misk", "sandal ağacı", "tonka"] } },

  // PARFUMS DE MARLY (10)
  { name: "Layton", brand: "Parfums de Marly", family: "yogun", notes: { top: ["elma", "lavanta", "bergamot", "mandalina"], mid: ["geranium", "menekşe", "yasemin"], base: ["vanilya", "karabiber", "sandal ağacı", "guaiac ağacı", "patchouli"] } },
  { name: "Herod", brand: "Parfums de Marly", family: "yogun", notes: { top: ["tarçın", "karabiber"], mid: ["tütün yaprağı", "tütsü", "osmanthus", "labdanum"], base: ["vanilya", "iso e super", "misk", "sedir", "cypriol yağı", "vetiver"] } },
  { name: "Percival", brand: "Parfums de Marly", family: "hafif", notes: { top: ["lavanta", "mandalina", "bergamot", "sardunya"], mid: ["menekşe", "kişniş", "yasemin", "tarçın", "hedione"], base: ["ambroxan", "amberwood", "misk", "balsam köknarı", "clearwood"] } },
  { name: "Sedley", brand: "Parfums de Marly", family: "hafif", notes: { top: ["limon", "nane", "bergamot", "greyfurt", "mandalina"], mid: ["lavanta", "biberiye", "geranium", "olibanum"], base: ["ambroxan", "sandal ağacı", "vetiver", "sedir", "kaşmir", "patchouli"] } },
  { name: "Pegasus", brand: "Parfums de Marly", family: "yogun", notes: { top: ["heliotrope", "kimyon", "bergamot"], mid: ["acı badem", "lavanta", "yasemin"], base: ["vanilya", "sandal ağacı", "amber"] } },
  { name: "Carlisle", brand: "Parfums de Marly", family: "yogun", notes: { top: ["elma", "hindistan cevizi"], mid: ["tonka fasulyesi", "gül"], base: ["vanilya", "patchouli"] } },
  { name: "Greenley", brand: "Parfums de Marly", family: "hafif", notes: { top: ["yeşil elma", "kalabriya bergamotu", "mandalina"], mid: ["petitgrain", "kaşmir ağacı", "sedir", "pomarose", "menekşe"], base: ["meşe yosunu", "misk", "amberwood"] } },
  { name: "Galloway", brand: "Parfums de Marly", family: "hafif", notes: { top: ["narenciye", "karabiber"], mid: ["portakal çiçeği", "iris"], base: ["misk", "amber"] } },
  { name: "Oajan", brand: "Parfums de Marly", family: "yogun", notes: { top: ["tarçın", "bal", "osmanthus"], mid: ["benzoin", "labdanum", "amber", "artemisia"], base: ["tonka fasulyesi", "vanilya", "patchouli", "misk"] } },
  { name: "Delina", brand: "Parfums de Marly", family: "orta", notes: { top: ["litchi", "rvent", "bergamot", "hindistan cevizi"], mid: ["türk gülü", "peony", "petalia", "vanilya", "misk"], base: ["kaşmir", "haiti vetiveri", "sedir", "tütsü"] } },

  // GUERLAIN (10)
  { name: "L'Homme Idéal EDT", brand: "Guerlain", family: "orta", notes: { top: ["narenciye", "biberiye", "portakal çiçeği", "acı portakal"], mid: ["badem", "tonka fasulyesi"], base: ["deri", "sedir", "vetiver"] } },
  { name: "L'Homme Idéal EDP", brand: "Guerlain", family: "yogun", notes: { top: ["badem", "baharatlar", "lavanta", "bergamot", "biberiye", "kekik"], mid: ["kiraz", "vanilya", "tütsü", "bulgar gülü"], base: ["deri", "tonka fasulyesi", "sandal ağacı"] } },
  { name: "L'Homme Idéal Extreme", brand: "Guerlain", family: "yogun", notes: { top: ["badem", "pembe biber", "bergamot"], mid: ["erik", "tarçın", "helyotrop"], base: ["tütün", "deri", "patchouli", "sedir"] } },
  { name: "Habit Rouge", brand: "Guerlain", family: "orta", notes: { top: ["limon", "brezilya gül ağacı", "portakal", "bergamot", "kireç", "mandalina", "fesleğen"], mid: ["gül", "karanfil", "sandal ağacı", "tarçın", "patchouli", "yasemin", "sedir"], base: ["vanilya", "deri", "amber", "benzoin", "meşe yosunu", "labdanum"] } },
  { name: "Vétiver Guerlain", brand: "Guerlain", family: "hafif", notes: { top: ["bergamot", "tütün", "limon", "hindistan cevizi", "neroli", "kişniş", "mandalina"], mid: ["vetiver", "karabiber", "karanfil", "adaçayı", "sandal ağacı", "orris kökü"], base: ["vetiver", "meşe yosunu", "deri", "mür", "misk", "tonka", "amber"] } },
  { name: "Heritage", brand: "Guerlain", family: "yogun", notes: { top: ["lavanta", "ardıç meyveleri", "aldahitler", "bergamot", "adaçayı", "petitgrain", "limon", "menekşe", "portakal"], mid: ["patchouli", "kişniş", "geranium", "karabiber", "pembe biber", "gül", "karanfil", "yasemin", "siklamen", "vadi zambağı"], base: ["sandal ağacı", "amber", "meşe yosunu", "sedir", "misk"] } },
  { name: "Shalimar", brand: "Guerlain", family: "yogun", notes: { top: ["narenciye", "bergamot", "limon", "sedir", "mandalina"], mid: ["iris", "patchouli", "vetiver", "yasemin", "gül"], base: ["vanilya", "tütsü", "deri", "opoponax", "sandal ağacı", "misk", "civet", "tonka"] } },
  { name: "Aqua Allegoria Pamplelune", brand: "Guerlain", family: "hafif", notes: { top: ["greyfurt", "limon"], mid: ["cassia", "petitgrain", "neroli"], base: ["patchouli", "vanilya"] } },
  { name: "Aqua Allegoria Bergamote Calabria", brand: "Guerlain", family: "hafif", notes: { top: ["kalabriya bergamotu", "petitgrain"], mid: ["kakule", "zencefil"], base: ["odunsu notalar", "beyaz misk"] } },
  { name: "L'Instant de Guerlain pour Homme", brand: "Guerlain", family: "orta", notes: { top: ["limon", "bergamot", "anason", "greyfurt", "elemi"], mid: ["çay", "yasemin", "hibiskus"], base: ["kakao", "patchouli", "sandal ağacı", "sedir", "misk"] } },

  // LOUIS VUITTON (10)
  { name: "Imagination", brand: "Louis Vuitton", family: "orta", notes: { top: ["citron", "bergamot", "portakal"], mid: ["zencefil", "tarçın", "neroli"], base: ["black tea", "ambroxan", "guaiac wood", "olibanum"] } },
  { name: "L'Immensité", brand: "Louis Vuitton", family: "hafif", notes: { top: ["greyfurt", "zencefil", "bergamot"], mid: ["su notaları", "adaçayı", "biberiye", "geranium"], base: ["ambroxan", "amber", "labdanum"] } },
  { name: "Afternoon Swim", brand: "Louis Vuitton", family: "hafif", notes: { top: ["mandalina", "sicilya portakalı", "bergamot"], mid: [], base: [] } },
  { name: "Ombre Nomade", brand: "Louis Vuitton", family: "yogun", notes: { top: ["oud", "gül", "ahududu", "safran"], mid: ["huş ağacı", "tütsü"], base: ["amberwood", "benzoin", "sandal ağacı"] } },
  { name: "Météore", brand: "Louis Vuitton", family: "hafif", notes: { top: ["mandalina", "sicilya portakalı", "kalabriya bergamotu"], mid: ["pembe biber", "biber", "guatemala kakulesi", "endonezya hindistan cevizi", "tunus nerolisi"], base: ["java vetiver yağı"] } },
  { name: "On The Beach", brand: "Louis Vuitton", family: "hafif", notes: { top: ["yuzu", "neroli"], mid: ["biberiye", "pembe biber", "kekik", "kum", "karanfil"], base: ["selvi"] } },
  { name: "Orage", brand: "Louis Vuitton", family: "orta", notes: { top: ["bergamot", "greyfurt"], mid: ["iris", "hedione", "karabiber"], base: ["patchouli", "java vetiver yağı", "iso e super", "beyaz misk"] } },
  { name: "Au Hasard", brand: "Louis Vuitton", family: "orta", notes: { top: ["bergamot", "limon", "aldahitler"], mid: ["kardelen", "armut", "neroli", "yeşil notalar", "frezye"], base: ["sandal ağacı", "deri", "misk", "kaşmir ağacı", "ambrette"] } },
  { name: "Nouveau Monde", brand: "Louis Vuitton", family: "yogun", notes: { top: ["agarwood (oud)", "kakao", "safran", "gül"], mid: ["deri", "amberwood"], base: ["olibanum", "vanilya"] } },
  { name: "Pacific Chill", brand: "Louis Vuitton", family: "hafif", notes: { top: ["portakal", "citron", "nane", "limon", "kişniş", "siyah frenk üzümü"], mid: ["kayısı", "fesleğen", "havlıcan", "mayıs gülü"], base: ["incir", "hurma", "ambrette"] } },

  // YSL (10)
  { name: "La Nuit de L'Homme", brand: "Yves Saint Laurent", family: "orta", notes: { top: ["kakule"], mid: ["lavanta", "sedir", "bergamot"], base: ["kimyon", "vetiver"] } },
  { name: "Y Eau de Parfum", brand: "Yves Saint Laurent", family: "orta", notes: { top: ["elma", "zencefil", "bergamot"], mid: ["adaçayı", "ardıç meyveleri", "geranium"], base: ["amberwood", "tonka fasulyesi", "sedir", "vetiver", "olibanum"] } },
  { name: "Y Le Parfum", brand: "Yves Saint Laurent", family: "yogun", notes: { top: ["elma", "aldahitler", "greyfurt", "zencefil"], mid: ["adaçayı", "lavanta", "geranium"], base: ["tonka fasulyesi", "sedir", "olibanum", "patchouli"] } },
  { name: "MYSLF", brand: "Yves Saint Laurent", family: "orta", notes: { top: ["kalabriya bergamotu", "bergamot"], mid: ["tunus portakal çiçeği"], base: ["ambrofix", "patchouli"] } },
  { name: "L'Homme", brand: "Yves Saint Laurent", family: "hafif", notes: { top: ["zencefil", "bergamot", "limon"], mid: ["baharatlar", "menekşe yaprağı", "beyaz biber", "fesleğen"], base: ["tonka fasulyesi", "sedir", "tahiti vetiveri"] } },
  { name: "Kouros", brand: "Yves Saint Laurent", family: "yogun", notes: { top: ["aldahitler", "artemisia", "kişniş", "adaçayı", "bergamot"], mid: ["patchouli", "karanfil", "geranium", "vetiver", "yasemin", "tarçın", "orris kökü"], base: ["misk", "bal", "deri", "civet", "meşe yosunu", "amber", "tonka", "vanilya"] } },
  { name: "Tuxedo", brand: "Yves Saint Laurent", family: "yogun", notes: { top: ["menekşe yaprağı", "kişniş", "bergamot"], mid: ["gül", "karabiber", "vadi zambağı"], base: ["patchouli", "ambergris", "bourbon vanilyası"] } },
  { name: "Caban", brand: "Yves Saint Laurent", family: "orta", notes: { top: ["elemi", "karabiber", "pembe biber"], mid: ["olibanum", "osmanthus"], base: ["sandal ağacı", "tonka fasulyesi"] } },
  { name: "Caftan", brand: "Yves Saint Laurent", family: "yogun", notes: { top: ["pembe biber", "bergamot", "tangerine"], mid: ["benzoin", "olibanum", "styrax"], base: ["labdanum", "misk"] } },
  { name: "Y Eau Fraiche", brand: "Yves Saint Laurent", family: "hafif", notes: { top: ["limon", "zencefil", "karabiber"], mid: ["geranium", "adaçayı", "ardıç meyveleri", "lavanta"], base: ["sedir", "olibanum"] } },

  // BVLGARI (10)
  { name: "Tygar", brand: "Bvlgari", family: "yogun", notes: { top: ["greyfurt"], mid: ["odunsu notalar"], base: ["ambroxan"] } },
  { name: "Aqva Pour Homme", brand: "Bvlgari", family: "hafif", notes: { top: ["mandalina", "portakal", "petitgrain"], mid: ["deniz yosunu", "lavanta", "pamuk çiçeği"], base: ["sedir", "odunsu notalar", "patchouli", "adaçayı", "amber"] } },
  { name: "Aqva Pour Homme Atlantiqve", brand: "Bvlgari", family: "hafif", notes: { top: ["su notaları", "kalabriya bergamotu", "sicilya limonu", "adaçayı"], mid: ["deniz notaları", "ambergris", "elma"], base: ["benzoin", "amberwood", "vetiver", "patchouli", "sandal ağacı"] } },
  { name: "Bvlgari Man In Black", brand: "Bvlgari", family: "yogun", notes: { top: ["baharatlar", "rom", "tütün"], mid: ["deri", "iris", "sümbülteber"], base: ["guaiac ağacı", "benzoin", "tonka fasulyesi"] } },
  { name: "Bvlgari Man Wood Essence", brand: "Bvlgari", family: "orta", notes: { top: ["narenciye", "limon otu", "kişniş yaprağı"], mid: ["sedir", "vetiver", "selvi"], base: ["benzoin"] } },
  { name: "Bvlgari Man Glacial Essence", brand: "Bvlgari", family: "hafif", notes: { top: ["ardıç meyveleri", "zencefil", "geranium"], mid: ["artemisia", "sandal ağacı", "orris kökü"], base: ["misk", "clearwood", "sedir"] } },
  { name: "Bvlgari Man Terrae Essence", brand: "Bvlgari", family: "orta", notes: { top: ["citron", "calamansi"], mid: ["vetiver", "orris kökü"], base: ["toprak notaları", "styrax"] } },
  { name: "Bvlgari Man Rain Essence", brand: "Bvlgari", family: "hafif", notes: { top: ["yeşil çay", "portakal"], mid: ["beyaz lotus", "misk"], base: ["kehribar", "guaiac ağacı"] } },
  { name: "Orom", brand: "Bvlgari", family: "yogun", notes: { top: ["bourbon vanilyası"], mid: ["siyam benzoin"], base: ["agarwood (oud)"] } },
  { name: "Gyan", brand: "Bvlgari", family: "yogun", notes: { top: ["yasemin sambac"], mid: ["patchouli"], base: ["tütsü"] } },

  // EKSTRALAR (Önceki listeden korunması gerekenler)
  { name: "God of Fire", brand: "Stephane Humbert Lucas 777", family: "yogun", notes: { top: ["mango", "limon", "pembe biber", "zencefil"], mid: ["mavi nilüfer", "yasemin", "odunsu notalar"], base: ["oud", "amber", "misk"] } },
  { name: "Arabians Tonka", brand: "Montale", family: "yogun", notes: { top: ["safran", "bergamot"], mid: ["oud", "bulgar gülü"], base: ["tonka fasulyesi", "şeker kamışı", "amber", "beyaz misk", "meşe yosunu"] } },
  { name: "Blue Talisman", brand: "Ex Nihilo", family: "orta", notes: { top: ["bergamot", "zencefil", "mandalina", "armut"], mid: ["portakal çiçeği", "georgiewood"], base: ["akigalawood", "misk", "amberbroxan"] } },
  { name: "Ganymede", brand: "Marc-Antoine Barrois", family: "yogun", notes: { top: ["mandalina"], mid: ["osmanthus", "menekşe", "safran"], base: ["akigalawood", "immortelle"] } },
  { name: "Invictus EDT", brand: "Paco Rabanne", family: "hafif", notes: { top: ["deniz notaları", "greyfurt", "mandalina"], mid: ["defne yaprağı", "yasemin"], base: ["gri amber", "guaiac ağacı", "meşe yosunu", "patchouli"] } },
  { name: "Paradise Garden", brand: "Jean Paul Gaultier", family: "orta", notes: { top: ["yeşil notalar", "nane", "zencefil"], mid: ["tuz", "incir", "adaçayı"], base: ["sandal ağacı", "tonka"] } },
  { name: "Spicebomb EDT", brand: "Viktor & Rolf", family: "orta", notes: { top: ["pembe biber", "elemi", "bergamot", "greyfurt"], mid: ["tarçın", "safran", "paprika"], base: ["tütün", "deri", "vetiver"] } },
  { name: "The One EDT", brand: "Dolce & Gabbana", family: "orta", notes: { top: ["kişniş", "fesleğen", "greyfurt"], mid: ["zencefil", "portakal çiçeği", "kakule"], base: ["tütün", "amber", "sedir"] } },
  { name: "Followed", brand: "Kerosene", family: "yogun", notes: { top: ["kahve"], mid: ["karamel", "çikolata"], base: ["vanilya", "amber"] } }
];